#!/bin/sh
_CONDA_ROOT="D:/geofarm_epic1_starter/mamba"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"
